### PR TITLE
Add CircuitBreaker to fail fast when serviceB fails repeatedly

### PR DESCRIPTION
**Pull request by tevans78**
Signed-off-by: Tom Evans <tevans@uk.ibm.com>

### CODE REVIEW

**Comment by pilhuhn** [comment]
While I think that the implementation is ok, I wonder if we really need this, as it would be Istio's task to provide the circuit-breaking. 
The counterpart to this one ( https://github.com/eclipse/microprofile-service-mesh-service-b/pull/13 ) certainly makes sense though, as it is needed to better/easier trigger the Circuit Breaker.

**Comment by kenfinnigan** [comment]
+1, usage in Service Mesh shouldn't showcase these types of settings.

Unless they're being added to show them being disabled in a Service Mesh?

**Comment by Emily-Jiang** [comment]
yes, Ken. Demonstrate the ecosystem is the intention. As we are trying to demonstrate the ecosystem, we need to fully utilise the FT functionalities. We create this situation and then create an ecosystem by setting the property if Istio FT rule is in place.

**Comment by kenfinnigan** [comment]
My concern is that what we're treating as an exercise in experimentation and finding out what issues MP has in a Service Mesh, others will treat as an example on how to do it in a Service Mesh.

I think we should discuss this further in the call tomorrow

**Comment by Emily-Jiang** [comment]
As discussed in last week's call, we left this PR for Jon to comment. Jon is ok for this to be merged.

**Pull request merged**
