### PR TITLE
Add jsonp and mpRestClient

### PR DESCRIPTION
**Pull request by tevans78**
Signed-off-by: Tom Evans <tevans@uk.ibm.com>

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
@tevans78 please create an issue to track this change.

**Comment by tevans78** [comment]
fixes #13

**Comment by Emily-Jiang** [comment]
Agreed to merge on the hangout today.

**Comment by kenfinnigan** [comment]
Was the content of this PR discussed in the meetings at all?

It's over complicating the example by pulling all the code out of the JAX-RS endpoint class. And I don't agree with adding a dependent Bean to add fallback annotations to it. Doesn't it circumvent REST Client usage by providing an implementation?

**Pull request merged**
